#!/bin/sh
# iperf3 runit run: start iperf3 server under a dynamic unprivileged user
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin"
export PATH

exec run-dynamic-user --service iperf3 -- iperf3 -s -1
