#!/bin/sh
# Prerequisites (FreeBSD):
#   pw useradd -n iperf3 -c "iperf3 service" -s /usr/sbin/nologin -d /nonexistent -w no
# Prerequisites (Void Linux):
#   useradd -c "iperf3 service" -s /usr/sbin/nologin -d /nonexistent -M -r -U iperf3
exec chpst -u iperf3 iperf3 -s
